version: '3.8'

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /usr/src/app/entrypoint.sh
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 1337:80
    restart: always
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
